### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by smith6jt-cop** [Onetism/AutoDeconJ#2]
Hello,

I am running in a new conda environment, Windows 10, admin anaconda prompt, VS 2017, CUDA 11.2.  Installed maven with conda.  The build created the .jar file with errors.  Running the test image in ImageJ gives:

(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 315MB of 48921MB (<1%)
 
java.lang.UnsatisfiedLinkError: Error while loading native library "JCudaRuntime-0.9.0d-windows-x86_64"
Operating system name: Windows 10
Architecture         : amd64
Architecture bit size: 64
---(start of nested stack traces)---
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no JCudaRuntime-0.9.0d-windows-x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
	at java.lang.Runtime.loadLibrary0(Runtime.java:872)
	at java.lang.System.loadLibrary(System.java:1124)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:143)
	at jcuda.runtime.JCuda.initialize(JCuda.java:422)
	at jcuda.runtime.JCuda.<clinit>(JCuda.java:406)
	at jcuda.driver.JCudaDriver.<clinit>(JCudaDriver.java:293)
	at Auto_LF_Deconvolution.start_run(Auto_LF_Deconvolution.java:178)
	at Auto_LF_Deconvolution.run(Auto_LF_Deconvolution.java:137)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)

I reran mvn clean package with -e and -X and here is the file
[AutoDeconJ_DEBUG.txt](https://github.com/Onetism/AutoDeconJ/files/13728990/AutoDeconJ_DEBUG.txt)

Could this be an issue with my CUDA version?  The ReadMe says CUDA 8 or higher, but maybe I need v9.0?

**Comment by Onetism** [comment]
Yes, you can choose to install CUDA 9.0 or upgrade [jcuda version](https://github.com/jcuda/jcuda?tab=readme-ov-file)
