### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by smith6jt-cop** [Onetism/AutoDeconJ#4]
Perhaps this is something I am doing incorrectly running build_cuda.but.  Using Windows 10, I run the file and get an error that the files should be in src/java/kernel, but the files are actually in src/main/resources.  My solution is to copy the files and create new directories, then the build xxx.cu to xxx.ptx proceeds as expected.

**Comment by smith6jt-cop** [comment]
Maybe this isn't a good idea.  I try to run the test data and get an error:


Exception in thread "Thread-6" jcuda.CudaException: CUDA_ERROR_INVALID_PTX
	at KernelLauncher.checkResult(KernelLauncher.java:647)
	at KernelLauncher.initModule(KernelLauncher.java:433)
	at KernelLauncher.load(KernelLauncher.java:196)
	at Kernelsetup.cudaFilesetup(Auto_LF_Deconvolution.java:1756)
	at Psfcompute_Thread.run(Auto_LF_Deconvolution.java:1855)

Here is my info:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:42:34_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0

PC with two Quadro K620, 2GB each

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: C:\Program Files\apache-maven-3.9.6
Java version: 17.0.9, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Onetism** [comment]
> Maybe this isn't a good idea. I try to run the test data and get an error:
> 
> Exception in thread "Thread-6" jcuda.CudaException: CUDA_ERROR_INVALID_PTX at KernelLauncher.checkResult(KernelLauncher.java:647) at KernelLauncher.initModule(KernelLauncher.java:433) at KernelLauncher.load(KernelLauncher.java:196) at Kernelsetup.cudaFilesetup(Auto_LF_Deconvolution.java:1756) at Psfcompute_Thread.run(Auto_LF_Deconvolution.java:1855)
> 
> Here is my info:
> 
> nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2023 NVIDIA Corporation Built on Tue_Jun_13_19:42:34_Pacific_Daylight_Time_2023 Cuda compilation tools, release 12.2, V12.2.91 Build cuda_12.2.r12.2/compiler.32965470_0
> 
> PC with two Quadro K620, 2GB each
> 
> Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: C:\Program Files\apache-maven-3.9.6 Java version: 17.0.9, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

I believe there might be two main issues: 1) The CUDA version may be too high, for example, you're using CUDA 12, while the version supported by jcuda might not have been updated to this latest version. The pom.xml file specifies CUDA 10.0, so adjustments will be needed during compilation. 2) The Java version might be too high; for instance, you're using Java 17, while ImageJ only supports Java 8.

The most convenient process to try is as follows:

1. Install CUDA 10.0.0 and then run the build_cuda file.
2. Download relevant files for jcuda version 10.0 and copy them in the plugins folder of ImageJ.
3. Compile AutoDeconJ and copy the AutoDeconJ_Plugin-jar-with-dependencies.jar file in the plugins folder of ImageJ.
4. Restart ImageJ.
